#!/bin/sh

# dmenu_run improved
# command ending with '!', is started in the terminal.
# Choose menu program based on session
if [ "$XDG_SESSION_TYPE" = "wayland" ] && command -v bemenu >/dev/null 2>&1; then
  MENU="bemenu"
  TERMINAL="foot"
else
  MENU="dmenu"
  TERMINAL="st"
fi

test -s "$HOME"/.dmenurc && . "$HOME"/.dmenurc

cmd="$(dmenu_path | $MENU -i "$@")"

case $cmd in
    '')  ;;
    *\!) exec "${TERMINAL:-st}" -e ${cmd%?} & ;;
    *)   exec ${cmd} & ;;
esac
