#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command cargo add/lang/rust

install_xbps_packages \
    base-devel \
    curl \
    emacs-gtk3 \
    fd \
    git \
    pandoc \
    ripgrep \
    texlab \
    tinymist \
    tree-sitter-cli \
    unzip \
    xz

"$add_root/lang/tex"
"$add_root/lang/typst"
