#!/usr/bin/env bash

set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command flatpak add/flathub

install_flatpak_apps flathub com.github.tchx84.Flatseal
