#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command flatpak add/flathub

install_xbps_packages \
    libdrm-32bit \
    lutris \
    steam

install_flatpak_apps flathub org.prismlauncher.PrismLauncher
