#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    curl \
    fd \
    fzf \
    gcc \
    git \
    make \
    neovim \
    ripgrep \
    tree-sitter-cli \
    unzip \
    xdg-utils \
    xz

"$add_root/lang/rust"
