#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

sudo xbps-install -Sy base-devel clang

"$add_root/pack/shell"
"$add_root/pack/tmux"
"$add_root/pack/nvim"
"$add_root/lang/node"
"$add_root/pack/codeberg"
