#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages base-devel clang

"$add_root/pack/shell"
"$add_root/pack/tmux"
"$add_root/pack/nvim"
"$add_root/lang/node"
"$add_root/pack/codeberg"
"$add_root/pack/github"
