#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    calibre \
    zathura \
    zathura-cb \
    zathura-djvu \
    zathura-pdf-poppler
