#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    bash-completion \
    bat \
    curl \
    dust \
    eza \
    fd \
    fzf \
    qalculate \
    ripgrep \
    stow \
    unzip \
    wget \
    xdg-utils

bat cache --build
