#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    nwg-look \
    yaru \
    papirus-icon-theme \
    nerd-fonts \
    noto-fonts-ttf \
    noto-fonts-cjk \
    noto-fonts-emoji
