#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages xtools

git clone --depth=1 https://github.com/void-linux/void-packages.git ~/.local/pkgs
cd ~/.local/pkgs
./xbps-src binary-bootstrap
