#!/usr/bin/env bash
set -euo pipefail

REPO=git@github.com:BeedPro/void-packages.git
DES=$HOME/Projects/BeedPro/void-packages

sudo xbps-install -Sy xtools

git clone --depth=1 --no-single-branch $REPO $DES
cd $DES
git remote add upstream https://github.com/void-linux/void-packages.git
./xbps-src binary-bootstrap
