#!/usr/bin/env bash

set -euo pipefail

PACKAGES=(
  xorg-minimal
  dbus-x11
  firefox
  rofi
  alacritty
  gucharmap
  mediainfo
  acpi
  gpick
  brightnessctl
  pulseaudio-utils
  libnotify
  NetworkManager
  network-manager-applet
  xfce-polkit
  aspell
  aspell-en
  qalculate
  qalculate-gtk
  adwaita-qt
  yaru
  papirus-icon-theme
  picom
  feh
  xss-lock
  dunst
  maim
  setxkbmap
  xclip
  xdotool
  dex
  i3
  i3blocks
  i3lock
  dragon
  peaclock
)

sudo xbps-install -Syu
sudo xbps-install -Sy "${PACKAGES[@]}"
