#!/usr/bin/env bash

set -euo pipefail

PACKAGES=(
  mpd
  mpc
  mpv
  nsxiv
  zathura
  zathura-djvu
  zathura-cb
  xournalpp
  farbfeld
)

sudo xbps-install -Syu
sudo xbps-install -Sy "${PACKAGES[@]}"

mkdir -p "$HOME/.local/share/mpd/playlists"
mkdir -p "$HOME/.cache/mpd"
mkdir -p "$HOME/.config/mpd"
