#!/bin/sh
nm-applet &
gtk-launch syncthing-start &
dunst &
mpd
/usr/libexec/xfce-polkit &

keepassxc &
flatpak run com.borgbase.Vorta &

xss-lock --transfer-sleep-lock -- slock --nofork &
picom -b
espanso-x11 start --unmanaged
$HOME/.screenlayout/screens.sh
xset dpms 0 0 0 && xset s noblank  && xset s off
