local map = vim.keymap.set

map("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "[D]ap [C]ontinue" })
map("n", "<leader>dn", function()
  require("dap").step_over()
end, { desc = "[D]ap [N]ext (Step Over)" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "[D]ap [I]nto (Step Into)" })
map("n", "<leader>do", function()
  require("dap").step_out()
end, { desc = "[D]ap [O]ut (Step Out)" })

map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "[D]ap Toggle [B]reakpoint" })
map("n", "<leader>dB", function()
  require("dap").set_breakpoint()
end, { desc = "[D]ap Set [B]reakpoint" })
map("n", "<leader>dr", function()
  require("dap").repl.open()
end, { desc = "[D]ap [R]epl Open" })
map("n", "<leader>dl", function()
  require("dap").run_last()
end, { desc = "[D]ap Run [L]ast" })
map("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "[D]ap [T]erminate" })
