# theme: light

[urgency_low]
    background = "#ffffff"
    foreground = "#000000"
    frame_color = "#3548cf"

[urgency_normal]
    background = "#ffffff"
    foreground = "#000000"
    frame_color = "#3548cf"

[urgency_critical]
    background = "#ffffff"
    foreground = "#a0132f"
    frame_color = "#a0132f"
