#!/usr/bin/env bash
set -euo pipefail

sudo xbps-remove -Ry \
    fzf \
    tmux \
    ncurses-term \
    rustup \
    volta \
    openjdk25 \
    tree-sitter-cli \
    neovim \
    emacs \
    emacs-gtk3 \
    binutils \
    curl \
    gcc \
    gmp-devel \
    glibc-devel \
    libffi-devel \
    make \
    ncurses-devel \
    ncurses-libtinfo-libs \
    ncurses-libtinfo-devel \
    perl \
    zlib-devel \
    pkg-config \
    base-devel \
    libsecret-devel \
    tar \
    xz

rm -rf "$HOME/.ghcup" "$HOME/.cabal" "$HOME/.stack" "$HOME/.volta" "$HOME/.cargo" "$HOME/.opencode"
rm -f "$HOME/.local/bin/opencode"
