#!/usr/bin/env bash
set -euo pipefail

sudo xbps-remove -Ry \
    i3 \
    i3blocks \
    i3lock-color \
    rofi \
    dex \
    alacritty \
    playerctl \
    maim \
    slop \
    xclip \
    xsel \
    dunst \
    picom \
    feh \
    jq \
    bc \
    acpi \
    lm_sensors \
    xsettingsd \
    arandr \
    xss-lock \
    xdg-desktop-portal-gtk \
    xdotool
