#!/bin/bash
set -euo pipefail

sudo systemctl disable --now kanata.service || true

if command -v cargo >/dev/null 2>&1; then
  cargo uninstall kanata || true
fi

sudo rm -f /usr/bin/kanata
sudo rm -rf /etc/kanata
sudo rm -f /etc/systemd/system/kanata.service
sudo systemctl daemon-reload

echo "Removed kanata"
