#!/usr/bin/env bash
set -euo pipefail

sudo xbps-remove -Ry \
  linux-firmware-nvidia \
  nvidia \
  nvidia-libs-32bit \
  libdrm-32bit \
  libgcc-32bit \
  libstdc++-32bit \
  libglvnd-32bit \
  vulkan-loader \
  vulkan-loader-32bit

sudo reboot
