#!/bin/bash
set -euo pipefail

# sudo rm -f /usr/local/lib/x86_64-linux-gnu/pkgconfig/rofi.pc
sudo rm -f /usr/local/share/man/man1/rofi.1
sudo rm -rf /usr/local/share/rofi
sudo rm -f /usr/local/share/applications/rofi.desktop
sudo rm -f /usr/local/share/icons/hicolor/scalable/apps/rofi.svg
sudo rm -f /usr/local/bin/rofi
sudo rm -rf /usr/local/include/rofi

echo "Removed selected rofi files"
