#!/usr/bin/env bash
set -euo pipefail

sudo rm -f /usr/local/bin/espanso-x11 /opt/Espanso-X11.AppImage
rm -rf "$HOME/.local/pkgs"

flatpak remote-delete --system --force flathub || true

sudo xbps-remove -Ry \
    wireguard-tools \
    xdg-utils \
    openresolv \
    xtools \
    unzip \
    speech-dispatcher \
    ncurses-term \
    bash-completion \
    brightnessctl \
    stow \
    fd \
    ripgrep \
    dust \
    eza \
    bat \
    git-lfs \
    python3-pipx \
    curl \
    wget \
    fzf \
    tmux \
    qalculate \
    flatpak \
    qalculate-gtk \
    scrcpy \
    gucharmap \
    syncthing \
    timeshift \
    keepassxc \
    zathura \
    nsxiv \
    calibre \
    mpv \
    mpd \
    rofi

sudo reboot
