# Dark
set $base        #000000
set $text        #ffffff
set $surface2    #303030
set $overlay0    #989898

set $accent      #2fafff
set $indicator   #feacd0
set $alert       #ff5f59
set $warning     #fec43f

# class                  border      bg         text     indicator    child_border
client.focused           $accent     $accent    $base    $indicator   $accent
client.focused_inactive  $surface2   $base      $text    $surface2    $surface2
client.unfocused         $surface2   $base      $text    $surface2    $surface2
client.urgent            $warning    $warning   $base    $overlay0    $warning
client.placeholder       $overlay0   $accent    $base    $overlay0    $overlay0
client.background        $base

bar {
  status_command i3blocks
  colors {
    background         $base
    statusline         $text
    focused_statusline $text
    focused_separator  $base

    # target           border    bg        text
    focused_workspace  $accent   $accent   $base
    active_workspace   $surface2 $surface2 $text
    inactive_workspace $surface2 $surface2 $text
    urgent_workspace   $alert    $alert    $base
  }
  mode dock
  modifier none
  tray_output DP-4
  tray_output eDP-1
}
