# Light
set -g pane-border-style fg=colour8
set -g pane-active-border-style fg=colour8

set -g status-style bg="#C8C8C8",fg=colour0
set -g mode-style bg="#A6A6A6",fg=colour0

set -g status-left ""
set -g status-right "#(whoami)@#H :: #S"
set -g status-left-length 100
set -g status-right-length 100

set -g window-status-format "#[bg=#E0E0E0] #I:#W#F "
set -g window-status-current-format "#[fg=colour15,bg=colour4] #I:#W#F "
set -g window-status-separator ""
