#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
  linux-firmware-amd \
  mesa-dri \
  mesa-vulkan-radeon \
  vulkan-loader \
  libglvnd-32bit \
  mesa-dri-32bit \
  mesa-vulkan-radeon-32bit \
  vulkan-loader-32bit

sudo reboot
