#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
  linux-firmware-amd \
  mesa-dri \
  mesa-vulkan-radeon \
  vulkan-loader \
  libglvnd-32bit \
  mesa-dri-32bit \
  mesa-vulkan-radeon-32bit \
  vulkan-loader-32bit

sudo reboot
