#!/bin/bash

sudo apt install dunst
sudo apt install xss-lock

sudo apt install cava
sudo apt install cmatrix
sudo apt install cbonsai
sudo apt install fastfetch

sudo apt install nwg-look
sudo apt install mpd
sudo apt install mpc
sudo apt install mpv
sudo apt install nsxiv
sudo apt install picom
sudo apt install feh
sudo apt install xournalpp
sudo apt install zathura
sudo apt install tmux
sudo apt install policykit-1-gnome
sudo apt install network-manager network-manager-applet
sudo apt install curl
sudo apt install farbfeld
sudo apt install git
sudo apt install libfcft-dev
sudo apt install borgbackup
sudo apt install vim
sudo apt install acpi
sudo apt install brightnessctl
sudo apt install libnotify-bin
sudo apt install pulseaudio-utils
sudo apt install pulsemixer
sudo apt install aspell aspell-en

sudo apt install maim
sudo apt install xkb-utils
sudo apt install xclip
sudo apt install xdotool
