#!/bin/bash
sudo apt update

CORE_UTILS=(
  bash-completion
  tmux
  vim
  git
  curl
  stow
  eza
  bat
  fd-find
  ripgrep
  du-dust
  git-lfs
  python3-venv
  pipx
  rofi
  qalc
  alacritty
)

SYSTEM=(
  acpi
  brightnessctl
  pulseaudio-utils
  libnotify-bin
  network-manager
  network-manager-applet
  lxpolkit
  aspell
  aspell-en
)

X11_TOOLS=(
  picom
  feh
  xss-lock
  dunst
  nwg-look
  maim
  x11-xkb-utils
  xclip
  xdotool
)

MEDIA=(
  mpd
  mpc
  mpv
  nsxiv
  zathura
  xournalpp
  libavcodec-extra
  farbfeld
)

THEME=(
  adwaita-qt
  adwaita-icon-theme-full
  gnome-themes-extra
)

echo "Installing all packages..."
sudo apt install -y "${CORE_UTILS[@]}" "${SYSTEM[@]}" "${X11_TOOLS[@]}" "${MEDIA[@]}" "${THEME[@]}"

if [ -f /usr/bin/batcat ]; then
  sudo ln -sf /usr/bin/batcat /usr/local/bin/bat
fi

if [ -f /usr/bin/fdfind ]; then
  sudo ln -sf /usr/bin/fdfind /usr/local/bin/fd
fi

if [ -f /usr/bin/mpd ]; then
  mkdir -p $HOME/.local/share/mpd/playlists
  mkdir -p $HOME/.cache/mpd
  mkdir -p $HOME/.config/mpd
fi

echo "Installation complete!"
