#!/bin/bash


# Initialise
PROJECT_DIR=$HOME/.local/src/AdnanHodzic
PROJECT=$PROJECT_DIR/auto-cpufreq
mkdir -p $PROJECT_DIR
cd $PROJECT_DIR

# Dependencies
sudo apt update
sudo apt-get install ninja-build gettext cmake curl build-essential lua5.3 liblua5.3-dev

# Clone
git clone --depth 1 https://github.com/AdnanHodzic/auto-cpufreq.git $PROJECT
cd $PROJECT

# Build
sudo ./auto-cpufreq-installer

# Clean up
rm -rf $PROJECT_DIR
echo "Removed auto-cpufreq source files"
echo "Installed auto-cpufreq"
