#!/bin/bash

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

LASTCHANGE_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media"

REVISION=$(curl -s -S $LASTCHANGE_URL)

echo "latest revision is $REVISION"

if [ -d /opt/chromium/$REVISION ] ; then
  echo "already have latest version"
  rm -rf "$TEMP_DIR"
  exit
fi

ZIP_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F$REVISION%2Fchrome-linux.zip?alt=media"

ZIP_FILE="${REVISION}-chrome-linux.zip"

echo "fetching $ZIP_URL"

mkdir $REVISION
pushd $REVISION
curl -# $ZIP_URL > $ZIP_FILE
echo "unzipping.."
unzip $ZIP_FILE
popd

sudo mkdir -p /opt/chromium
sudo rm -rf /opt/chromium/$REVISION
sudo mv $REVISION /opt/chromium/$REVISION

sudo rm -rf /opt/chromium/latest
sudo ln -s /opt/chromium/$REVISION/chrome-linux /opt/chromium/latest

sudo rm -f /usr/local/bin/chromium
sudo ln -s /opt/chromium/latest/chrome /usr/local/bin/chromium

rm -rf "$TEMP_DIR"
