#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

sudo xbps-install -Syu
sudo xbps-install -Sy fuse-sshfs

"$script_dir/pde"
"$script_dir/mpd"
"$script_dir/wireguard"
"$script_dir/void-packages"
"$script_dir/ai"
