#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    base-devel \
    bash-completion \
    bat \
    curl \
    eza \
    fd \
    fzf \
    git \
    ncurses-term \
    neovim \
    ripgrep \
    rustup \
    stow \
    tmux \
    tree-sitter-cli \
    unzip \
    volta \
    xdg-utils \
    xz

bat cache --build
volta install node
rustup-init -y --no-modify-path
