#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    base-devel \
    bash-completion \
    bat \
    dust \
    eza \
    fd \
    fuse-sshfs \
    git-lfs \
    ncurses-term \
    neovim \
    qalculate \
    ripgrep \
    rustup \
    stow \
    tmux \
    tree-sitter-cli \
    volta \
    wget \
    wireguard-tools \
    xdg-utils \
    xtools

bat cache --build
volta install node
rustup-init -y --no-modify-path
