#!/usr/bin/env bash
set -euo pipefail

# tags: #dev

command -v nix >/dev/null 2>&1 || { echo "nix not installed"; exit 1; }

nix profile add nixpkgs#devenv
sudo mkdir -p /nix/var/nix
sudo ln -s /var/nix/daemon-socket /nix/var/nix/daemon-socket
