#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    binutils \
    curl \
    gcc \
    gmp-devel \
    glibc-devel \
    libffi-devel \
    make \
    ncurses-devel \
    ncurses-libtinfo-libs \
    ncurses-libtinfo-devel \
    perl \
    zlib-devel \
    pkg-config \
    base-devel \
    libsecret-devel \
    tar \
    xz \
    rustup \
    volta \
    openjdk25

volta install node
rustup-init --no-modify-path
