#!/bin/bash
set -euo pipefail

sudo apt update
sudo apt install -y extrepo

sudo extrepo update
sudo extrepo enable docker-ce

sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker $USER
