#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    fzf \
    tmux \
    ncurses-term \
    rustup \
    volta \
    tree-sitter-cli \
    neovim \
    emacs \
    emacs-gtk3

sudo xbps-install -Sy \
    binutils \
    curl \
    gcc \
    gmp-devel \
    glibc-devel \
    libffi-devel \
    make \
    ncurses-devel \
    ncurses-libtinfo-libs \
    perl \
    pkg-config \
    tar \
    xz

curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

volta install node
rustup-init --no-modify-path
