#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -S \
    fzf \
    tmux \
    ncurses-term \
    rustup \
    tree-sitter-cli \
    neovim \
    emacs \
    emacs-gtk3

echo ""
echo "Make sure to run the rustup-init to install rust toolkit"
