#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -S \
    fzf \
    tmux \
    ncurses-term \
    rustup \
    volta \
    tree-sitter-cli \
    neovim \
    emacs \
    emacs-gtk3

volta install node
rustup-init --no-modify-path
