#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

sudo xbps-install -Syu

sudo xbps-install -Sy \
    base-devel \
    curl \
    emacs-gtk3 \
    fd \
    git \
    pandoc \
    ripgrep \
    texlab \
    tinymist \
    tree-sitter-cli \
    unzip \
    xz

"$script_dir/tex"
"$script_dir/typst"
