#!/bin/bash

# Initialise
PROJECT_DIR=$HOME/.local/src/emacs
PROJECT=$PROJECT_DIR/emacs-30.1
mkdir -p $PROJECT_DIR
cd $PROJECT_DIR

# Dependencies
sudo apt update
sudo apt-get build-dep emacs

# Download Emacs source
wget https://ftp.gnu.org/pub/gnu/emacs/emacs-30.1.tar.gz
tar -axvf emacs-30.1.tar.gz

# Build
cd $PROJECT
./autogen.sh
./configure --with-native-compilation --with-tree-sitter CFLAGS="-O2 -pipe -march=native -fomit-frame-pointer"
make -j$(nproc)
sudo make install

git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.config/emacs
$HOME/.config/emacs/bin/doom install
$HOME/.config/emacs/bin/doom sync

# Clean up
rm -rf $PROJECT_DIR
echo "Removed Emacs 30.1 source files"
echo "Installed Emacs 30.1"
