#!/usr/bin/env bash

set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

install_xbps_packages flatpak

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

sudo reboot
