#!/usr/bin/env bash
set -euo pipefail

sudo apt update
sudo apt install -y flatpak gnome-software-plugin-flatpak

sudo flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# flatpak remote-add --if-not-exists unmojang https://unmojang.github.io/unmojang-flatpak/index.flatpakrepo

echo "Flatpak installed and Flathub added. Log out and back in if apps do not appear yet."
