#!/usr/bin/env bash

set -euo pipefail

sudo xbps-install -Syu
sudo xbps-install -Sy flatpak

flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

sudo reboot
flatpak install -y flathub com.github.tchx84.Flatseal
