#!/bin/bash

if ! command -v getnf >/dev/null 2>&1; then
  curl -fsSL https://raw.githubusercontent.com/getnf/getnf/main/install.sh | bash
fi

getnf -i Gohu
cp $HOME/.dotfiles/.local/share/fonts/Gohu/GohuFont14NerdFont-Italic.ttf $HOME/.local/share/fonts/Gohu
