#!/bin/sh
set -eu

# tags: #pkg

command -v flatpak >/dev/null 2>&1 || { echo "flatpak is not installed. Run add/flathub first."; exit 1; }

sudo xbps-install -Sy \
    libdrm-32bit \
    lutris \
    steam

flatpak install -y flathub org.prismlauncher.PrismLauncher
