#!/usr/bin/env bash
set -euo pipefail

if ! command -v wget >/dev/null 2>&1; then
  sudo apt update
  sudo apt install -y wget
fi

out="$(mktemp)"
trap 'rm -f "$out"' EXIT

sudo mkdir -p -m 0755 /etc/apt/keyrings
wget -nv -O "$out" https://cli.github.com/packages/githubcli-archive-keyring.gpg
sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg < "$out" > /dev/null
sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

sudo mkdir -p -m 0755 /etc/apt/sources.list.d
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

sudo apt update
sudo apt install -y gh
