#!/bin/bash

sudo apt update

sudo apt install build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev libncurses6 libtinfo6 pkg-config

curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
