#!/bin/sh
set -eu

# tags: #pkg

sudo xbps-install -Sy godot godot-export-templates

mkdir -p "$HOME/.local/share/godot"
ln -sfn /usr/lib/godot/export_templates "$HOME/.local/share/godot/export_templates"
