#!/bin/bash

# Ensure unzip is installed
if ! command -v unzip &> /dev/null; then
    echo "unzip not found. Installing unzip..."
    sudo apt update && sudo apt install -y unzip
else
    echo "unzip is already installed."
fi

# Downloading Grayjay Desktop
cd /tmp || exit
echo "Downloading Grayjay Desktop..."
wget https://updater.grayjay.app/Apps/Grayjay.Desktop/Grayjay.Desktop-linux-x64.zip

# Unzipping
echo "Unzipping Grayjay..."
unzip Grayjay.Desktop-linux-x64.zip

# Move to /opt
sudo rm -rf /opt/grayjay
sudo mv Grayjay.Desktop-linux-x64-v9 /opt/grayjay

# Create symlink if executable exists
sudo ln -sf /opt/grayjay/Grayjay /usr/local/bin/grayjay
echo "Grayjay linked to /usr/local/bin/grayjay"

# Cleanup
rm -f /tmp/grayjay.zip
echo "Cleaned up temporary files"
