#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu
sudo xbps-install -Sy curl unzip zip

curl -s "https://get.sdkman.io" | bash

# shellcheck disable=SC1091
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk install groovy
