#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v flatpak >/dev/null 2>&1; then
    echo "flatpak is not installed. Run add/flathub first."
    exit 1
fi

sudo xbps-install -Syu

sudo xbps-install -Sy gucharmap xournalpp

"$script_dir/firefox"
"$script_dir/readers"
"$script_dir/media"
"$script_dir/flatseal"
"$script_dir/vorta"
"$script_dir/espanso"
