#!/bin/sh
set -eu

# tags: #app

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

command -v flatpak >/dev/null 2>&1 || { echo "flatpak is not installed. Run add/flathub first."; exit 1; }

sudo xbps-install -Sy gucharmap xournalpp gpick

"$add_root/firefox"
"$add_root/readers"
"$add_root/media"
"$add_root/flatseal"
"$add_root/vorta"
"$add_root/espanso"
"$add_root/emacs"
"$add_root/obs"
"$add_root/printers"
