#!/bin/bash

echo "Downloading Helium AppImage"
cd /tmp
wget https://github.com/imputnet/helium-linux/releases/download/0.7.7.1/helium-0.7.7.1-x86_64.AppImage
chmod +x /tmp/helium-0.7.7.1-x86_64.AppImage

sudo mv /tmp/helium-0.7.7.1-x86_64.AppImage /opt
sudo ln -sf /opt/helium-0.7.7.1-x86_64.AppImage /usr/local/bin/helium
echo "Linked to /usr/local/bin"
echo "Helium downloaded"

