#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    arandr \
    bc \
    brightnessctl \
    dex \
    dunst \
    feh \
    i3 \
    i3blocks \
    i3lock-color \
    alacritty \
    libnotify \
    lm_sensors \
    maim \
    picom \
    playerctl \
    python3 \
    rofi \
    setxkbmap \
    slop \
    acpi \
    jq \
    xclip \
    xdotool \
    xrandr \
    xsel \
    xss-lock \
    xdg-desktop-portal-gtk \
    xsettingsd
