#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    i3 \
    i3blocks \
    i3lock \
    rofi \
    dex \
    alacritty \
    playerctl \
    maim \
    slop \
    xclip \
    xsel \
    dunst \
    picom \
    feh \
    jq \
    bc \
    acpi \
    lm_sensors \
    xsettingsd \
    gsettings-desktop-schemas \
    xdotool
