#!/bin/bash
set -euo pipefail

sudo install -d -m 0755 /etc/apt/keyrings

echo -e "Types: deb\nURIs: https://download.opensuse.org/repositories/home:/strycore:/lutris/Debian_13/\nSuites: ./\nComponents: \nSigned-By: /etc/apt/keyrings/lutris.gpg" | sudo tee /etc/apt/sources.list.d/lutris.sources >/dev/null
wget -q -O- https://download.opensuse.org/repositories/home:/strycore:/lutris/Debian_13/Release.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/lutris.gpg

sudo apt update
sudo apt install -y lutris

echo "Lutris installed successfully"
