#!/bin/bash

# Download the Mullvad signing key
sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc

# Add the Mullvad repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable stable main" | sudo tee /etc/apt/sources.list.d/mullvad.list

# Install the package
sudo apt update
sudo apt install mullvad-vpn

sudo ln -sf "/opt/Mullvad VPN/mullvad-vpn" /usr/local/bin/mullvad-vpn
sudo ln -sf "/opt/Mullvad VPN/mullvad-gui" /usr/local/bin/mullvad-gui
