#!/bin/bash


# Initialise
PROJECT_DIR=$HOME/.local/src/neovim
PROJECT=$PROJECT_DIR/neovim
mkdir -p $PROJECT_DIR
cd $PROJECT_DIR

# Dependencies
sudo apt update
sudo apt-get install ninja-build gettext cmake curl build-essential lua5.3 liblua5.3-dev

# Clone
git clone --depth 1 -b v0.11.3 https://github.com/neovim/neovim $PROJECT
cd $PROJECT

# Build
rm -rfv build/
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

# Clean up
rm -rf $PROJECT_DIR
echo "Removed neovim source files"
echo "Installed neovim"
