#!/bin/bash
set -euo pipefail


# Dependencies
sudo apt update
sudo apt-get install ninja-build gettext cmake curl build-essential lua5.3 liblua5.3-dev luajit

# Build in a temp directory
BUILD_DIR=$(mktemp -d)
trap 'rm -rf $BUILD_DIR' EXIT

cd "$BUILD_DIR"
git clone --depth 1 -b v0.12.3 https://github.com/neovim/neovim .
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

echo "Installed neovim"
