#!/usr/bin/env bash
set -euo pipefail

# tags: #dev

sudo xbps-install -Sy nix

sudo ln -sfn /etc/sv/nix-daemon /var/service/nix-daemon

sudo sv up nix-daemon

nix profile add nixpkgs#devenv

sudo mkdir -p /nix/var/nix
sudo ln -s /var/nix/daemon-socket /nix/var/nix/daemon-socket
