#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
  linux-firmware-nvidia \
  nvidia \
  nvidia-libs-32bit \
  libdrm-32bit \
  libstdc++-32bit \
  vulkan-loader \
  vulkan-loader-32bit

sudo reboot
