#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
  linux-firmware-nvidia \
  nvidia \
  nvidia-libs-32bit \
  libdrm-32bit \
  libstdc++-32bit \
  vulkan-loader \
  vulkan-loader-32bit

sudo reboot
