#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -Sy \
    curl \
    fd \
    fzf \
    gcc \
    git \
    make \
    neovim \
    ripgrep \
    rustup \
    tree-sitter-cli \
    unzip \
    xdg-utils \
    xz

rustup-init -y --no-modify-path
