#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

sudo xbps-install -Syu

sudo xbps-install -Sy \
    curl \
    fd \
    fzf \
    gcc \
    git \
    make \
    neovim \
    ripgrep \
    tree-sitter-cli \
    unzip \
    xdg-utils \
    xz

"$script_dir/rust"
