#!/bin/sh
set -eu

# tags: #pkg

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

sudo xbps-install -Sy \
    curl \
    fd \
    fzf \
    gcc \
    git \
    make \
    neovim \
    ripgrep \
    tree-sitter-cli \
    unzip \
    xdg-utils \
    xz

"$add_root/rust"
