#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

sudo xbps-install -Syu
sudo xbps-install -Sy base-devel

"$script_dir/shell"
"$script_dir/tmux"
"$script_dir/nvim"
"$script_dir/node"
