#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
  tlp \
  powertop \
  acpi \
  brightnessctl

sudo ln -sfn /etc/sv/tlp /var/service/

sudo reboot
