#!/bin/bash
set -euo pipefail

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

curl -fsSLo "$tmpdir/protonvpn-stable-release_1.0.8_all.deb" https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.8_all.deb
echo "0b14e71586b22e498eb20926c48c7b434b751149b1f2af9902ef1cfe6b03e180 $tmpdir/protonvpn-stable-release_1.0.8_all.deb" | sha256sum --check -
sudo dpkg -i "$tmpdir/protonvpn-stable-release_1.0.8_all.deb"
sudo apt update
