#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

read -rp "Set up QEMU/KVM as host or guest? [host] " role
role="${role:-host}"

case "$role" in
host | h)
    install_xbps_packages \
        qemu \
        libvirt \
        virt-manager \
        virt-viewer \
        dnsmasq \
        bridge-utils \
        iptables \
        edk2-ovmf \
        swtpm

    sudo ln -sfn /etc/sv/dbus /var/service/dbus
    sudo ln -sfn /etc/sv/libvirtd /var/service/libvirtd
    sudo ln -sfn /etc/sv/virtlogd /var/service/virtlogd
    sudo ln -sfn /etc/sv/virtlockd /var/service/virtlockd

    sudo usermod -aG libvirt,kvm "$USER"
    sudo reboot
    ;;
guest | g)
    install_xbps_packages spice-vdagent
    sudo ln -sfn /etc/sv/spice-vdagentd /var/service/spice-vdagentd
    sudo reboot
    ;;
*)
    echo "Expected host or guest."
    exit 1
    ;;
esac
