#!/bin/sh
set -eu

# tags: #pkg

sudo xbps-install -Sy \
    bash-completion \
    bat \
    peaclock \
    curl \
    xxd \
    dust \
    eza \
    fd \
    fzf \
    qalculate \
    ripgrep \
    stow \
    unzip \
    wget \
    xdg-utils \
    clang \
    cmake

bat cache --build
sudo chsh -s /bin/bash root
sudo sh -c 'cat "$1" > /root/.bashrc' sh "$HOME/.dotfiles/.bashrc.root"
