#!/bin/bash

sudo apt update

sudo apt build-dep dwm
sudo apt install libfribidi-dev libimlib2-dev libgd-dev libfcft-dev libxrandr-dev


echo "------------------ dwm -------------------------"
cd $HOME/.dotfiles/.local/share/dwm
sudo make clean install

echo "------------------ dmenu -------------------------"
cd $HOME/.dotfiles/.local/share/dmenu
sudo make clean install

echo "------------------ st -------------------------"
cd $HOME/.dotfiles/.local/share/st
sudo make clean install

echo "------------------ slock -------------------------"
cd $HOME/.dotfiles/.local/share/slock
sudo make clean install

echo "------------------ dwmblocks -------------------------"
cd $HOME/.dotfiles/.local/share/dwmblocks
sudo make clean install

echo "------------------ sent -------------------------"
cd $HOME/.dotfiles/.local/share/sent
sudo make clean install
