#!/usr/bin/env bash
set -euo pipefail

TT_VERSION="v0.4.2"

sudo curl -fsSL "https://github.com/lemnos/tt/releases/download/${TT_VERSION}/tt-linux" -o /usr/local/bin/tt
sudo chmod 0755 /usr/local/bin/tt

sudo install -d -m 0755 /usr/share/man/man1
sudo curl -fsSL "https://github.com/lemnos/tt/releases/download/${TT_VERSION}/tt.1.gz" -o /usr/share/man/man1/tt.1.gz
