#!/usr/bin/env bash
set -euo pipefail

# tags: #dev

command -v cargo >/dev/null 2>&1 || { echo "cargo is not installed. Run add/rust first."; exit 1; }

sudo xbps-install -Sy typst

cargo install --git=https://github.com/antonWetzel/prettypst.git --locked

ln -sfn $HOME/.cargo/bin/prettypst $HOME/.local/bin/prettypst
