#!/bin/bash
set -euo pipefail

sudo apt update
sudo apt install pkg-config libssl-dev
cargo install --locked typst-cli
cargo install --git https://github.com/Myriad-Dreamin/tinymist --locked tinymist-cli
cargo install --git=https://github.com/antonWetzel/prettypst.git --locked

sudo ln -sf $HOME/.cargo/bin/tinymist /usr/local/bin/tinymist
sudo ln -sf $HOME/.cargo/bin/prettypst /usr/local/bin/prettypst
