#!/bin/bash
set -e

cd /tmp

wget -O ueberzugpp.deb \
  https://download.opensuse.org/repositories/home:/justkidding/Debian_13/amd64/ueberzugpp_2.9.8_amd64.deb

sudo apt install ./ueberzugpp.deb

rm ueberzugpp.deb
