#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -S \
    unzip \
    speech-dispatcher \
    brightnessctl \
    stow \
    curl \
    flatpak

sudo xbps-install -S \
    syncthing \
    timeshift \
    keepassxc \
    rofi

flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

sudo reboot
