#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu

sudo xbps-install -S \
    unzip \
    speech-dispatcher \
    bash-completion \
    brightnessctl \
    stow \
    curl \
    fzf \
    tmux \
    flatpak

sudo xbps-install -S \
    syncthing \
    timeshift \
    keepassxc \
    rofi

flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

git clone --depth=1 https://github.com/void-linux/void-packages.git ~/.local/pkgs
cd ~/.local/pkgs
~/.local/pkgs/xbps-src binary-bootstrap

sudo reboot
