#!/bin/sh
set -eu

# tags: #pkg

REPO=git@github.com:beedware/void-packages.git
DES=$HOME/Projects/beedware/void-packages

sudo xbps-install -Sy xtools

git clone --depth=1 --no-single-branch $REPO $DES
git clone --depth=1 https://github.com/void-linux/void-packages.git $HOME/Projects/void-linux/void-packages
cd $DES
git remote add upstream https://github.com/void-linux/void-packages.git
./xbps-src binary-bootstrap
