#!/usr/bin/env bash
set -euo pipefail

sudo xbps-install -Syu
sudo xbps-install -Sy git xtools

git clone --depth=1 https://github.com/void-linux/void-packages.git ~/.local/pkgs
cd ~/.local/pkgs
./xbps-src binary-bootstrap
