#!/usr/bin/env bash
set -euo pipefail

# tags: #pkg

command -v flatpak >/dev/null 2>&1 || { echo "flatpak is not installed. Run add/flathub first."; exit 1; }

sudo xbps-install -Sy borg

flatpak install -y flathub com.borgbase.Vorta
