#!/usr/bin/env bash

set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$add_root/common/utils"

# Lock root account
sudo -v
sudo true
sudo passwd -l root

# System update and repositories
install_xbps_packages \
    void-repo-nonfree \
    void-repo-multilib \
    void-repo-multilib-nonfree \
    linux-firmware

# XFCE4 packages
install_xbps_packages \
    firefox \
    dbus-x11 \
    psmisc \
    cronie \
    xorg \
    xfce4 \
    xfce4-plugins \
    xfce4-screenshooter \
    lightdm \
    lightdm-gtk-greeter \
    gvfs \
    ntfs-3g \
    exfatprogs \
    udisks2

# Desktop permissions and networking
install_xbps_packages \
    network-manager-applet

# Audio and Bluetooth
install_xbps_packages \
    pipewire \
    wireplumber \
    alsa-pipewire \
    pamixer \
    libspa-bluetooth \
    blueman

# ALSA compatibility for PipeWire
sudo mkdir -p /etc/alsa/conf.d
sudo ln -sfn /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/50-pipewire.conf
sudo ln -sfn /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/99-pipewire-default.conf

cd ~/.dotfiles
ln -sfn ../.dotfiles/.config/autostart ~/.config/autostart
ln -sfn ../.dotfiles/.config/pipewire ~/.config/pipewire

# Start services after packages and config links are in place
sudo ln -sfn /etc/sv/dbus /var/service/dbus
sudo ln -sfn /etc/sv/elogind /var/service/elogind
sudo ln -sfn /etc/sv/lightdm /var/service/lightdm
sudo ln -sfn /etc/sv/polkitd /var/service/polkitd
sudo ln -sfn /etc/sv/cronie /var/service/cronie
sudo ln -sfn /etc/sv/NetworkManager /var/service/NetworkManager
sudo ln -sfn /etc/sv/bluetoothd /var/service/bluetoothd

# Add user to common desktop groups
sudo usermod -aG wheel,audio,video,input,storage,network,bluetooth "$USER"

"$add_root/pack/themes"

# Reboot to apply everything
sudo reboot
