#!/bin/bash

# Downloading source
cd /tmp

wget https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz

tar -axvf zen.linux-x86_64.tar.xz
sudo rm -rf /opt/zen
sudo mv zen /opt/

# Linking to /usr/local/bin
sudo ln -sf /opt/zen/zen /usr/local/bin/zen
echo "Linked to /usr/local/bin"

# Cleaning
rm -rf /tmp/zen.linux-x86_64.tar.xz
rm -rf /tmp/zen.linux-x86_64.tar.xz.1
rm -rf zen.linux-x86_64.tar.xz
echo "Cleaned up zen downloads"
