#!/bin/sh

OUTPUT=$(date '+%Y.%m.%d %H:%M:%S')
DIVIDER_FILE="$HOME/.config/i3blocks/divider"

if [ -r "$DIVIDER_FILE" ]; then
    IFS= read -r DIVIDER < "$DIVIDER_FILE"
fi

if [ -n "$DIVIDER" ]; then
    printf '%s %s\n' "$DIVIDER" "$OUTPUT"
else
    printf '%s\n' "$OUTPUT"
fi
