#!/bin/sh

choice=$(printf '%s\n' lock logout suspend hibernate reboot poweroff | rofi -dmenu)

if [ -f /tmp/power-lock ]; then
    notify-send "Powermenu" "Power locked due to process"
    exit 0
fi

if [ "$choice" = "logout" ]; then
    if [ "${XDG_SESSION_TYPE:-}" = "wayland" ] || [ -n "${SWAYSOCK:-}" ]; then
        swaymsg exit
    else
        i3-msg exit
    fi
elif [ "$choice" = "lock" ]; then
    "$HOME/.config/rofi/modes/locker"
elif [ -n "$choice" ]; then
    loginctl "$choice"
fi
