#!/usr/bin/env bash
set -euo pipefail

sudo apt remove -y firefox-esr
sudo apt-get update
sudo apt-get install -y extrepo

sudo extrepo update
sudo extrepo enable mozilla

echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla

sudo apt-get update
sudo apt-get install -y firefox
