#!/bin/bash

go install github.com/natsukagami/mpd-mpris/cmd/mpd-mpris@latest
mkdir -p $HOME/.config/systemd/user
ln -sf $HOME/.dotfiles/.config/systemd/user/mpd-mpris.service $HOME/.config/systemd/user/mpd-mpris.service
systemctl --user --now enable mpd-mpris
systemctl --user status mpd-mpris
