# theme: dark

[global]
background = "#000000"
foreground = "#ffffff"
frame_color = "#2fafff"
highlight = "#2fafff"
separator_color = frame
follow = mouse

[urgency_low]
frame_color = "#44bc44"
timeout = 5

[urgency_normal]
timeout = 5

[urgency_critical]
frame_color = "#ff5f59"

[rule]
appname = "peaclock"
background = "#000000"
foreground = "#ffffff"
frame_color = "#feacd0"
timeout = 10
