# theme: light

[global]
background = "#ffffff"
foreground = "#000000"
frame_color = "#0031a9"
highlight = "#0031a9"
separator_color = frame
follow = mouse

[urgency_low]
frame_color = "#006800"
timeout = 5

[urgency_normal]
timeout = 5

[urgency_critical]
frame_color = "#a60000"

[rule]
appname = "peaclock"
background = "#ffffff"
foreground = "#000000"
frame_color = "#721045"
timeout = 10
