#!/usr/bin/env bash

# Change brightness
case "$1" in
	up)
		brightnessctl set +5% >/dev/null
		;;
	down)
		brightnessctl set 5%- >/dev/null
		;;
esac

TITLE="Brightness"
BODY="lux --%"

# Check backlight exists
if [ -d /sys/class/backlight ] && [ "$(ls -A /sys/class/backlight 2>/dev/null)" ]; then
	percent=$(brightnessctl | grep -oP '\(\K[0-9]+(?=%)')

	if [ -n "$percent" ]; then
		# clamp visual bar
		bar_val=$percent
		[ "$bar_val" -gt 100 ] && bar_val=100
		[ "$bar_val" -lt 0 ] && bar_val=0

		BAR_WIDTH=35
		FILLED=$((bar_val * BAR_WIDTH / 100))
		EMPTY=$((BAR_WIDTH - FILLED))

		FILLED_BAR=$(printf '%*s' "$FILLED" '' | tr ' ' '|')
		EMPTY_BAR=$(printf '%*s' "$EMPTY" '' | tr ' ' '-')

		TITLE="Brightness ${percent}%"
		BODY="[${FILLED_BAR}${EMPTY_BAR}]"
	fi
fi

notify-send -r 9998 -t 1000 "$TITLE" "\n$BODY"
