#!/usr/bin/env sh

DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"
ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}" # alert if free space < 10%

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

df -h -P $LOCAL_FLAG "$DIR" | awk -v label="[/] " -v alert_low=$ALERT_LOW '
/\/.*/ {
	# use = percentage used (e.g. 73%)
	use = $5

	# full and short text: print used percentage
	print label use
	print label use

	# strip %
	gsub(/%$/, "", use)

	# alert if space remaining is too low
	if (100 - use < alert_low) {
		print "#FF0000"
	}
	exit 0
}
'
