#!/usr/bin/env bash

paths=(/ /mnt/nvme /mnt/ssd)

for p in "${paths[@]}"; do
  if mountpoint -q "$p"; then
    df -h "$p" | awk 'NR==2 {
      printf "%-15s %8s / %-8s (%4s)\n", $6, $3, $2, $5
    }'
  fi
done
