#!/bin/sh

choice=$(printf '%s\n' lock logout suspend hibernate reboot poweroff | rofi -dmenu)

if [ -f /tmp/power-lock ]; then
    notify-send "Powermenu" "Power locked due to process"
    exit 0
fi

if [ "$choice" = "logout" ]; then
    pkill i3
elif [ "$choice" = "lock" ]; then
    "$HOME/.local/scripts/locker"
elif [ -n "$choice" ]; then
    loginctl "$choice"
fi
