#!/usr/bin/env bash

# Directory containing wallpaper folders
WALL_DIR="$HOME/Pictures/walls"

# Find all files one level deep in subdirectories, filter only images
wallpaper=$(find "$WALL_DIR" -mindepth 2 -maxdepth 2 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' \) \
    | shuf -n 1)

echo "$wallpaper"

