#!/usr/bin/env bash
set -euo pipefail

while true; do
  session="$(
    sesh list -t | fzf-tmux -p 80%,70% \
      --no-sort \
      --border-label " tmux sessions " \
      --prompt "> " \
      --header "enter: kill session | esc: cancel" \
      --border=sharp \
      --preview-border=left \
      --preview 'sesh preview {}' \
      --no-scrollbar \
      --preview-window 'right:55%' \
      --layout 'reverse' \
      --color=bg:-1,bg+:-1,preview-bg:-1 \
      --bind "tab:down,btab:up"
  )" || exit 0

  tmux kill-session -t "$session"
done
