#!/bin/bash

export XDG_CURRENT_DESKTOP=sway
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
/usr/libexec/xdg-desktop-portal-wlr &
/usr/libexec/xdg-desktop-portal -r &

