/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "fakefullscreenclient.h"
#include "fullscreen.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "sticky.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_deck.h"
#include "layout_monocle.h"
#include "layout_tile.h"

