#!/usr/bin/env bash

set -euo pipefail

sudo xbps-install -Syu
sudo xbps-install -S dbus elogind xorg xfce4 xfce4-plugins xfce4-screenshooter lightdm lightdm-gtk3-greeter
sudo xbps-install -S firefox
sudo xbps-install -S yaru papirus-icon-theme

sudo ln	-s /etc/sv/dbus /var/service
sudo ln	-s /etc/sv/elogind /var/service
sudo ln	-s /etc/sv/lightdm /var/service

sudo passwd -l root

sudo reboot
