#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages fuse-sshfs

"$add_root/pack/pde"
"$add_root/pack/mpd"
"$add_root/pack/wireguard"
"$add_root/pack/void-packages"
"$add_root/pack/ai"
