#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command flatpak add/flathub

install_xbps_packages gucharmap xournalpp

"$add_root/pack/firefox"
"$add_root/pack/readers"
"$add_root/pack/media"
"$add_root/pack/flatseal"
"$add_root/pack/vorta"
"$add_root/pack/espanso"
"$add_root/pack/emacs"
