#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    arandr \
    bc \
    brightnessctl \
    dex \
    dunst \
    feh \
    i3 \
    i3blocks \
    i3lock-color \
    alacritty \
    lm_sensors \
    maim \
    picom \
    playerctl \
    rofi \
    setxkbmap \
    acpi \
    jq \
    xclip \
    xdotool \
    xsel \
    xss-lock \
    xdg-desktop-portal-gtk \
    xsettingsd
