[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black = '#000000'
red = '#ff5f59'
green = '#44bc44'
yellow = '#d0bc00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#a6a6a6'

[colors.bright]
black = '#595959'
red = '#ff5f5f'
green = '#44df44'
yellow = '#efef00'
blue = '#338fff'
magenta = '#ff66ff'
cyan = '#00eff0'
white = '#ffffff'

[colors.selection]
background = '#2f3849'
foreground = '#ffffff'

[[colors.indexed_colors]]
index = 16
color = '#fec43f'

[[colors.indexed_colors]]
index = 17
color = '#ff6b55'
