#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

install_xbps_packages \
    curl \
    gcc \
    gmp-devel \
    libffi-devel \
    make \
    ncurses-devel \
    ncurses-libtinfo-devel \
    ncurses-libtinfo-libs \
    perl \
    xz \
    zlib-devel

curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
