#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command cargo add/lang/rust

install_xbps_packages texlive-full

cargo install tex-fmt --locked

ln -sfn $HOME/.cargo/bin/tex-fmt $HOME/.local/bin/tex-fmt
