#!/usr/bin/env bash
set -euo pipefail

if ! command -v cargo >/dev/null 2>&1; then echo "cargo is not installed. Run add/lang/rust first."; exit 1; fi

sudo xbps-install -Sy texlive-full

cargo install tex-fmt --locked

ln -sfn $HOME/.cargo/bin/tex-fmt $HOME/.local/bin/tex-fmt
