#!/usr/bin/env bash
set -euo pipefail

add_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$add_root/common/utils"

require_command cargo add/lang/rust

install_xbps_packages typst

cargo install --git=https://github.com/antonWetzel/prettypst.git --locked

ln -sfn $HOME/.cargo/bin/prettypst $HOME/.local/bin/prettypst
