#!/usr/bin/env bash

set -euo pipefail

sudo xbps-install -Syu
sudo xbps-install -Sy \
  docker \
  docker-compose

sudo ln -sfn /etc/sv/containerd /var/service/containerd
sudo ln -sfn /etc/sv/docker /var/service/docker
sudo usermod -aG docker "$USER"

printf '%s\n' \
  'Docker configured.' \
  'Log out and back in for new group memberships to apply.'
