#!/usr/bin/env bash

set -euo pipefail

PACKAGES=(
  dejavu-fonts-ttf
  gohufont
  nerd-fonts-ttf
  font-iosevka
  noto-fonts-ttf
  noto-fonts-emoji
)

sudo xbps-install -Syu
sudo xbps-install -Sy "${PACKAGES[@]}"
